version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    tty: true
    volumes:
      - .:/workspace:cached
      - ~/.ssh:/root/.ssh:cached
    ports:
      - '3000:3000'

  mongodb:
    extends:
      file: ../docker-compose.yaml
      service: mongodb
