name: pj-esc-001831

services:
  api:
    container_name: pj-esc-001831-api
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/api.Dockerfile
      args:
        - NODE_ENV=development
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USERNAME=${USERNAME:-developer}
    restart: unless-stopped
    extra_hosts:
      - "co-maker.storage:192.168.1.12"
    depends_on:
      storage:
        condition: service_healthy
      database:
        condition: service_healthy
    volumes:
      - ../../:/workspace:cached
      - ./.docker/data:/data:cached
      - ~/.ssh:/home/${USERNAME:-developer}/.ssh:cached
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      pj-esc-001831-api-network:
        ipv4_address: 192.168.1.10

  database:
    container_name: pj-esc-001831-database
    build:
      context: ..
      dockerfile: ./docker/dockerfiles/postgres.Dockerfile
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 2s
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
      pj-esc-001831-api-network:
        ipv4_address: 192.168.1.11
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
      - .docker/postgres/certs:/var/lib/postgresql/certs

  storage:
    image: minio/minio
    container_name: pj-esc-001831-storage
    command: server /data --console-address ":9001"
    healthcheck:
      test: curl -f "http://localhost:9000/minio/health/live"
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - '9000:9000' # MinIO API
      - '9001:9001' # MinIO Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - .docker/minio:/data
    restart: unless-stopped
    networks:
      pj-esc-001831-api-network:
        ipv4_address: 192.168.1.12

networks:
  pj-esc-001831-api-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
